version: '3'

services:
  client:
    image: node:lts
    build:
      context: .
      dockerfile: Docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: yarn dev
    ports:
      - '3000:3000'
